## Before running, please make sure that you've already added all need tools excuceable path to your environment, including Picard ToolKit, GATK, BWA, XHMM and PSEQ.
## Please store or use the soft links to guarantee all the seqdata, reference annotations and output results would be stored in the same project directory.


#!/bin/bash
#===============================================================================
# xhmm Exome CNV Analysis Pipeline
#===============================================================================

set -euo pipefail

#-------------------------- Parameters --------------------------
REF_INDEX_DIR="${HOME}/EOSCZ/Ref_and_Index/"
REF_FA="${REF_INDEX_DIR}/gatk-hg38bundle/Homo_sapiens_assembly38.fa"
DICT="${REF_INDEX_DIR}/gatk-hg38bundle/Homo_sapiens_assembly38.dict"
BWA_INDEX="${REF_INDEX_DIR}/BWA_INDEX"
EXON="${REF_INDEX_DIR}/hg38_exon.merge.bed"
BED_FILE="${REF_INDEX_DIR}/T086V4_MT.merged.success.liftover.to.hg38.bed" # targer region bed files
SAMPLE_PATTERN="Sample_YangZHSCZ*.sample_interval_summary"

#-------------------------- Function --------------------------

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >&2
}

die() {
    log "ERROR: $*"
    exit 1
}

check_file() {
    [[ -f "$1" ]] || die "文件不存在: $1"
}

check_cmd() {
    command -v "$1" &>/dev/null || die "命令未找到: $1"
}

#-------------------------- Data preprocess --------------------------
# Step 1: Convert BED file to interval list and calculate the GC content 
preprocess_gc() {
    log "=== Step 1:  Convert BED file to interval list and calculate the GC content ==="

    # BED -> IntervalList
    java -jar picard.jar BedToIntervalList \
        I="$EXON" \
        O=EXOME.interval_list \
        SD="$DICT" || die "BedToIntervalList Failed"

    check_file EXOME.interval_list

    # Calculate the GC content for each interval
    java -Xmx3072m -jar gatk \
        -T GCContentByInterval \
        -L EXOME.interval_list \
        -R "$REF_FA" \
        -o locus_GC.txt || die "GCContentByInterval Failed"

    check_file locus_GC.txt

    # Filter out regions with extreme GC content (<10% 或 >90%)
    awk '{if ($2 < 0.1 || $2 > 0.9) print $1}' locus_GC.txt > extreme_gc_targets.txt
    log "Number of regions with extreme GC contents: $(wc -l < extreme_gc_targets.txt)"
}

# Step 2: Calculate the complexity of target regions
preprocess_complexity() {
    log "=== Step 2: Calculate the complexity of target regions ==="

    # IntervalList -> pseq reg format
    xhmm EXOME.interval_list > EXOME.targets.reg || die "interval_list_to_pseq_reg Failed"

    check_file EXOME.targets.reg

    pseq . loc-load \
        --locdb EXOME.targets.LOCDB \
        --file EXOME.targets.reg \
        --group targets \
        --out EXOME.targets.LOCDB.loc-load || die "loc-load 失败"

    # Select regions with low complexity (>25% repeat elements)
    pseq . loc-stats \
        --locdb EXOME.targets.LOCDB \
        --group targets \
        --seqdb seqdb | \
        awk '{if (NR > 1) print $_}' | \
        sort -k1 -g | \
        awk '{print $10}' | \
        paste EXOME.interval_list - | \
        awk '{print $1"\t"$2}' > DATA.locus_complexity.txt || die "loc-stats Failed"

    check_file DATA.locus_complexity.txt

    awk '{if ($2 > 0.25) print $1}' DATA.locus_complexity.txt > low_complexity_targets.txt
    log "Number of regions with low complexity: $(wc -l < low_complexity_targets.txt)"
}

#-------------------------- XHMM主流程 --------------------------
# Step 3: Merge the depths of all samples generated by GATK
merge_depths() {
    log "=== Step 3: Merge depths output of all samples ==="

    local depth_args=""
    for i in ../sample_interval_summary/$SAMPLE_PATTERN; do
        [[ -f "$i" ]] || continue
        depth_args="$depth_args --GATKdepths $i"
    done

    [[ -n "$depth_args" ]] || die "$i Sample_interval_summary file was not found."

    xhmm --mergeGATKdepths -o SCZ.RD.txt $depth_args || die "mergeGATKdepths Failed"
    check_file SCZ.RD.txt
}

# Step 4: Filter target regions and samples
filter_and_center() {
    log "=== Step 4: Filter target regions and samples ==="

    xhmm --matrix \
        -r SCZ.RD.txt \
        --centerData --centerType target \
        -o DATA.filtered_centered.RD.txt \
        --outputExcludedTargets ./DATA.filtered_centered.RD.txt.filtered_targets.txt \
        --outputExcludedSamples ./DATA.filtered_centered.RD.txt.filtered_samples.txt \
        --excludeTargets ./extreme_gc_targets.txt \
        --excludeTargets ./low_complexity_targets.txt \
        --minTargetSize 10 --maxTargetSize 10000 \
        --minMeanTargetRD 10 --maxMeanTargetRD 500 \
        --minMeanSampleRD 25 --maxMeanSampleRD 200 \
        --maxSdSampleRD 150 || die "matrix filtering/centering Failed"

    check_file DATA.filtered_centered.RD.txt
}

# Step 5: PCA analysis
run_pca() {
    log "=== Step 5: PCA analysis ==="

    xhmm --PCA \
        -r ./DATA.filtered_centered.RD.txt \
        --PCAfiles ./DATA.RD_PCA || die "PCA Failed"
}

# Step 6: PCA normalization
normalize_pca() {
    log "=== Step 6: PCA normalization ==="

    xhmm --normalize \
        -r ./DATA.filtered_centered.RD.txt \
        --PCAfiles ./DATA.RD_PCA \
        --normalizeOutput ./DATA.PCA_normalized.txt \
        --PCnormalizeMethod PVE_mean \
        --PVE_mean_factor 0.7 || die "normalize Failed"

    check_file ./DATA.PCA_normalized.txt
}

# Step 7: Z-score normalization (sample based)
zscore_center() {
    log "=== Step 7: Z-score normalization ==="

    xhmm --matrix \
        -r ./DATA.PCA_normalized.txt \
        --centerData --centerType sample \
        --zScoreData \
        -o ./DATA.PCA_normalized.filtered.sample_zscores.RD.txt \
        --outputExcludedTargets ./DATA.PCA_normalized.filtered.sample_zscores.RD.txt.filtered_targets.txt \
        --outputExcludedSamples ./DATA.PCA_normalized.filtered.sample_zscores.RD.txt.filtered_samples.txt \
        --maxSdTargetRD 30 || die "z-score centering Failed"

    check_file ./DATA.PCA_normalized.filtered.sample_zscores.RD.txt
}

# Step 8: Filter the raw data
sync_filter() {
    log "=== Step 8: Filter the raw data ==="

    xhmm --matrix \
        -r SCZ.RD.txt \
        --excludeTargets ./DATA.filtered_centered.RD.txt.filtered_targets.txt \
        --excludeTargets ./DATA.PCA_normalized.filtered.sample_zscores.RD.txt.filtered_targets.txt \
        --excludeSamples ./DATA.filtered_centered.RD.txt.filtered_samples.txt \
        --excludeSamples ./DATA.PCA_normalized.filtered.sample_zscores.RD.txt.filtered_samples.txt \
        -o ./DATA.same_filtered.RD.txt || die "sync filter Failed"

    check_file ./DATA.same_filtered.RD.txt
}

# Step 9: Detect CNV
discover_cnv() {
    log "=== Step 9: Detect CNV ==="

    xhmm --discover \
        -p ../params.txt \
        -r ./DATA.PCA_normalized.filtered.sample_zscores.RD.txt \
        -R ./DATA.same_filtered.RD.txt \
        -c ./DATA.xcnv \
        -a ./DATA.aux_xcnv \
        -s ./DATA || die "discover Failed"

    check_file ./DATA.xcnv
}

# Step 10: CNVg genotype
genotype_cnv() {
    log "=== Step 10: CNVg genotype ==="

    xhmm --genotype \
        -p ../params.txt \
        -r ./DATA.PCA_normalized.filtered.sample_zscores.RD.txt \
        -R ./DATA.same_filtered.RD.txt \
        -g ./DATA.xcnv \
        -F "$REF_FA" \
        -v ./SCZ_CNV.vcf || die "genotype 失败"

    check_file ./SCZ_CNV.vcf
    log "CNV analysis was completed！The output file is: SCZ_CNV.vcf"
}

#-------------------------- 主流程 --------------------------
main() {
    log "Start xhmm CNV analysis pipeline"
    log "工作目录: $(pwd)"
    log "Reference genome: $REF_FA"

    # Check the analysis tools
    check_cmd xhmm
    check_cmd java
    check_cmd $pseq

    # Check the input files
    check_file "$REF_FA"
    check_file "$DICT"
    check_file "$EXON"

    # Main excution
    preprocess_gc
    preprocess_complexity
    merge_depths
    filter_and_center
    run_pca
    normalize_pca
    zscore_center
    sync_filter
    discover_cnv
    genotype_cnv

    log "All steps were completed！"
}

# Breakpoint continuation
# Example: bash script.sh [start_step]
# start_step: gc|complexity|merge|filter|pca|normalize|zscore|sync|discover|genotype
START_STEP="${1:-}"

if [[ -n "$START_STEP" ]]; then
    log "Re-start from [$START_STEP] ..."
    case "$START_STEP" in
        gc)          preprocess_gc; preprocess_complexity; merge_depths; filter_and_center; run_pca; normalize_pca; zscore_center; sync_filter; discover_cnv; genotype_cnv ;;
        complexity)  preprocess_complexity; merge_depths; filter_and_center; run_pca; normalize_pca; zscore_center; sync_filter; discover_cnv; genotype_cnv ;;
        merge)       merge_depths; filter_and_center; run_pca; normalize_pca; zscore_center; sync_filter; discover_cnv; genotype_cnv ;;
        filter)      filter_and_center; run_pca; normalize_pca; zscore_center; sync_filter; discover_cnv; genotype_cnv ;;
        pca)         run_pca; normalize_pca; zscore_center; sync_filter; discover_cnv; genotype_cnv ;;
        normalize)   normalize_pca; zscore_center; sync_filter; discover_cnv; genotype_cnv ;;
        zscore)      zscore_center; sync_filter; discover_cnv; genotype_cnv ;;
        sync)        sync_filter; discover_cnv; genotype_cnv ;;
        discover)    discover_cnv; genotype_cnv ;;
        genotype)    genotype_cnv ;;
        *)           die "Unknown step: $START_STEP" ;;
    esac
else
    main
fi
